### ISSUE TITLE
raise error `make: *** No rule to make target `/var/lib/sf/roles/install/C7.0-J.1.4.0/cloud.done', needed by `/var/lib/sf/roles/install/C7.0-1.0.2/softwarefactory.done'.  Stop.` while run `SF_SKIP_FETCHBASES=1 ./build_roles.sh`

### ISSUE THREAD

**Issue by lawrancejing** [redhat-cip/software-factory#5]
I try to install SF in centos 7 via lxc , but it stopped in `SF_SKIP_FETCHBASES=1 ./build_roles.sh` http://softwarefactory.enovance.com/docs/deploy.html#fetch-pre-built-sf-images

####################OUTPUT########################
[root@i-dese1t2c software-factory]# SF_SKIP_FETCHBASES=1 SKIP_UPSTREAM=1 ./build_roles.sh
Already on 'master'
Already up-to-date.
Reset branch 'master'
Already on 'master'
Already up-to-date.
Reset branch 'master'

PREPARE SUBPROJECTS DIRECTORIES
This is a tagged release; using pinned versions of subprojects to build images.
Fetch PYSFLIB:0.2.0 in /root/software-factory/../deps/pysflib.
-> PYSFLIB head is: 7ce19ce Bump version prior to tagging 0.2.0
Fetch CAUTH:0.4.0 in /root/software-factory/../deps/cauth.
-> CAUTH head is: 3af2db0 Unified login endpoint
Fetch MANAGESF:0.4.0 in /root/software-factory/../deps/managesf.
-> MANAGESF head is: 76b4a8a Bump version prior to tagging 0.4.0

softwarefactory local hash is 20eea057e28215e169bb1800306d393c
The locally built softwarefactory md5 is different to what we computed from your git branch state.
Building role now...
make: *** No rule to make target `/var/lib/sf/roles/install/C7.0-J.1.4.0/cloud.done', needed by `/var/lib/sf/roles/install/C7.0-1.0.2/softwarefactory.done'.  Stop.

**Comment by cschwede** [comment]
Thanks for the bugreport!

Did you try to build it without the SF_SKIP_FETCHBASES setting? This setting will skip downloading the base role, and amongst others the C7.0-J.1.4.0/cloud role. You need to build this either manually or download once if it's not existing yet.

Could you please retry without the setting?

**Comment by lawrancejing** [comment]
@cschwede will try it now, and feedback soon

**Comment by lawrancejing** [comment]
no luck, it failed `make: *** [/var/lib/sf/roles/install/C7.0-1.0.2/softwarefactory.done] Error 127`

**Comment by lawrancejing** [comment]
ubuntu has the same  problem ...

**Comment by morucci** [comment]
Hi,

There are two cases: either use the master version of SF or the latest tag of SF. I suggest you to use the latest tag (today 1.0.2). When using a tag you are able to use prebuilt images of SF.

Unfortunately for the 1.0.2 of SF a little bug in our images checksum has been introduced so even if you use the 1.0.2 tag you need to rebuild the images.

So in order to build and deploy 1.0.2 on LXC (note that only centos 7 is supported now):
```
cd software-factory
git checkout 1.0.2
# ./fetch_roles.sh trees <- can be skip according to the bug I mentioned
./build_roles.sh
```

Once done you can continue here to deploy the LXC containers after the roles has been built:
http://softwarefactory.enovance.com/docs/deploy.html#how-to-deploy-sf-within-lxc

I hope it will help.

#softwarefactory on freenode

Cheers,
Fabien

**Comment by lawrancejing** [comment]
sorry for later reply , and i will try it now

**Comment by lawrancejing** [comment]
thanks  it works
